HLS Bounding Box Anti-meridian fix
nasa/opera-sds-pge pull request #293
Opened 2023-06-01 18:07 UTC by collinss-jpl

## Description
- This branch addresses an issue in the`metadata_utils.get_geographic_boundaries_from_mgrs_tile` function for tiles that crossed the anti-meridian. The function has been updated with fixes that were applied to the PCM version of the function, which were originally provided by Gustavo Shiroma.

## Affected Issues
- Fixes #291 

## Testing
- The following unit test has been added to validate that the anti-meridian case is now handled correctly:

```python
    def test_get_geographic_boundaries_from_mgrs_tile_nominal_antimeridian(self):
        """Test MGRS tile code conversion with a tile that crosses the anti-meridian"""
        lat_min, lat_max, lon_min, lon_max = get_geographic_boundaries_from_mgrs_tile('T60VXQ')

        self.assertAlmostEqual(lat_min, 62.13198085489144)
        self.assertAlmostEqual(lat_max, 63.16076767648831)
        self.assertAlmostEqual(lon_min, 178.82637550795243)
        self.assertAlmostEqual(lon_max, -179.06925552951074)
```

Note that the lat/lon values differ slightly from the test case provided in the original bug report. This is because as part of this fix, 4.9km of margin is now added to the bounding box footprint to bring it in line with the HLS standard.

2023-06-05 20:55 UTC, sjlewis-jpl commented on src/opera/util/metadata_utils.py
> +            if (offset_x_multiplier == 0 and
I think the if-statements for `lon_min` and `lon_max` could be simplified.  Add `offset_x_multiplier ==0 and ...` on the previous if-statement.  Something like this:
```
if (offset_x_multiplier == 0) and (lon_min is None or lon_min > lon):
    lon_min = lon
if (offset_x_multiplier == 1) and (lon_max is None or lon_max < lon):
    lon_max = lon
``` 

That should pick the `lon_min` from the two boundary points on the "left-hand" side of the granule (viewing when north is up), and `lon_max` from the two boundary points on the "right-hand" side.

2023-06-05 23:15 UTC, sjlewis-jpl requested changes
The change that I mentioned to the if-statements should be applied (https://github.com/nasa/opera-sds-pge/pull/293/files#r1218582327).  As is, the function gives the right answer for `lon_min`, but not for `lon_max`.

If you insert this line just after `transformation.TransformPoint` is called, you can see the lat/lon pairs of each corner:
```
print(offset_x_multiplier, offset_y_multiplier, x, y, lat, lon, z)
```
Then running the function shows this:
```
>>> get_geographic_boundaries_from_mgrs_tile('T60VXQ')
0 0 595100.0 6895100.0 62.17575213937371 178.82637550795243 0.0
0 1 595100.0 7004900.0 63.16076767648831 178.88808853630766 0.0
1 0 704900.0 6895100.0 62.13198085489144 -179.06925552951074 0.0
1 1 704900.0 7004900.0 63.11512337751825 -178.93677941363356 0.0
Out[25]: (62.13198085489144, 63.16076767648831, 178.82637550795243, -179.06925552951074)
```
From the printed lines, the furthest east point should be the largest of the two negative longitudes (i.e. the "least negative"), `-178.93677941363356`.  But it's giving the other as the `lon_max`.

If you swap out the if-statements for the ones in my earlier comment, you should see this:
```
>>> get_geographic_boundaries_from_mgrs_tile_new('T60VXQ')
0 0 595100.0 6895100.0 62.17575213937371 178.82637550795243 0.0
0 1 595100.0 7004900.0 63.16076767648831 178.88808853630766 0.0
1 0 704900.0 6895100.0 62.13198085489144 -179.06925552951074 0.0
1 1 704900.0 7004900.0 63.11512337751825 -178.93677941363356 0.0
Out[35]: (62.13198085489144, 63.16076767648831, 178.82637550795243, -178.93677941363356)
```
That one pulled the correct `lon_max`.

2023-06-05 23:15 UTC, sjlewis-jpl commented on src/opera/test/util/test_metadata_utils.py
> +        self.assertAlmostEqual(lon_max, -90.81751155385777)
I see why these changed (from lines 191 and 192 in the new function).  But it is a bit concerning that our lat/lon values seem to differ from the bounding polygons from the Sentinel-2 UTM Tiling Grid (HLS is supposed to be using the exact same tiling grid).  You can find a kml of that tiling grid here:  https://eatlas.org.au/data/uuid/f7468d15-12be-4e3f-a246-b2882a324f59

Grepping through that file for the tile IDs of the ones used in the unit tests (my grep commands copied below) shows slightly different lat/lon bounds.  I assume this is due to us using a slightly different projection for our calculations.  If these outputs are only used for showing bounding boxes in Earthdata Search, say, then probably not a big deal.  But worth a conversation with ADT.
```
grep -A 20 "15SXR" S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
grep -A 20 "60VXQ" S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml
```

2023-06-07 17:00 UTC, collinss-jpl commented
@sjlewis-jpl I've updated the conditionals for lon_max/lon_min according to your feedback, and ensured that the numbers I get match what you've posted. Let me know if anything else still looks off.

2023-06-07 18:56 UTC, sjlewis-jpl approved these changes

2023-06-07 20:42 UTC, merged