342 Ignore list for hdf5 metadata extraction utility
nasa/opera-sds-pge pull request #350
Opened 2023-08-24 19:02 UTC by david-inglish

## Description
- These changes implement a feature to exclude group Datasets from HDF5 files when retrieving metadata.  This will save on memory use where large Datasets are present in the group.
- CSLC-S1 has been updated to use the new feature.

## Affected Issues
- #342 

## Testing
- pytest assertions have been added to check that datasets have been ignored.

2023-08-28 17:42 UTC, JimHofman approved these changes
Looks good

2023-08-28 20:02 UTC, collinss-jpl requested changes
Very minor changes requested, but ones I'd like to see before this is merged

2023-08-28 20:02 UTC, collinss-jpl commented on src/opera/util/metadata_utils.py
> +    # Remove some of the larger arrays from the metadata, so we don't use
Lets change "Remove" to "Ignore" here

2023-09-05 16:05 UTC, collinss-jpl approved these changes

2023-09-05 16:05 UTC, merged