#348 add disp_s1 iso-metadata
nasa/opera-sds-pge pull request #367
Opened 2023-09-13 21:01 UTC by JimHofman

## Description
- Produce ISO XML metadata using jinja1 template

## Testing
- added a unit test (98% code coverage)

2023-09-13 22:47 UTC, david-inglish commented on src/opera/pge/disp_s1/disp_s1_pge.py
> +        # Find a single representative output DSWx-HLS product, they should all
DSWx-HLS -> DISP-S1

2023-09-13 22:51 UTC, david-inglish commented on src/opera/pge/disp_s1/disp_s1_pge.py
> +            'ISO_OPERA_ProjectKeywords': ['OPERA', 'JPL', 'DSWx', 'Dynamic', 'Surface', 'Water', 'Extent'],
Should these particular keywords be related to surface displacement?

2023-09-18 21:21 UTC, collinss-jpl requested changes
Implementation looks good, but the unit test needs a few more checks, and the changes to requirements.txt need to be reverted before merge.

2023-09-18 21:21 UTC, collinss-jpl commented on requirements.txt
Was this intended for inclusion? I want to keep the versions un-pinned in this file since we install into an existing environment within the SAS container.

2023-09-24 15:19 UTC, collinss-jpl approved these changes

2023-09-24 15:19 UTC, merged