Measured parameters fof DSWx-HLS
nasa/opera-sds-pge pull request #540
Opened 2024-10-27 20:42 UTC by JimHofman

## Description
- Added code for the Measured parameters for DSWx-HLS

## Affected Issues
- N/A
## Testing
- All pytest completed successfully

2024-10-31 14:21 UTC, RKuttruff requested changes
Code changes look good!
Could you please commit `pge/dswx_hls/templates/dswx_hls_measured_parameters.yaml` before merging?

2024-10-31 21:02 UTC, RKuttruff approved these changes

2024-11-04 18:14 UTC, collinss-jpl requested changes
While inspecting the ISO XML product created by this branch, I noticed several `MeasuredParameters` entries that had `!Not Found!` for one or more fields. I have tried to indicate what the missing entries are in my comments below.

2024-11-04 18:14 UTC, collinss-jpl commented on src/opera/pge/dswx_hls/templates/dswx_hls_measured_parameters.yaml
> +WORLDCOVER_COVERAGE:
Missing entry for WORLDCOVER_SOURCE

2024-11-14 21:19 UTC, RKuttruff commented
The `!Not found!` check passed unit tests because I accidentally used `!Not Found!` in the augment function (capital F not lowercase)
Will refactor to use a constant instead of literal strings at all checks

2024-11-14 23:34 UTC, RKuttruff commented on src/opera/pge/dswx_hls/templates/dswx_hls_measured_parameters.yaml
> +  description: HLS Fmask values to convert moderate-confidence water to high-confidence water in the presence of high aerosol
@collinss-jpl 
Turns out the `AEROSOL_PARTIAL_SURFACE_WATER_CONSERVATIVE_TO_HIGH_CONF_WATER_FMASK_VALUES` entry wasn't missing, it had the wrong display name. Perhaps a copy-paste error: it was displayed as a duplicate `AerosolWaterModerateConfToHighConfWaterFMaskValues` attribute.

2024-11-14 23:39 UTC, RKuttruff commented on src/opera/pge/dswx_hls/templates/dswx_hls_measured_parameters.yaml
> +  description: HLS Fmask values to convert moderate-confidence water to high-confidence water in the presence of high aerosol
It looks like this existed with the old version of the template:
![image](https://github.com/user-attachments/assets/9bb60f6e-ef21-4d05-8b7a-cf6ad3bdc2e6)

2024-11-20 17:39 UTC, collinss-jpl approved these changes
Looks good @RKuttruff, nice work diagnosing the issue with the missing/duplicate parameter in the original template.

2024-11-20 17:39 UTC, merged