Initial stub implementation for DIST-S1 PGE
nasa/opera-sds-pge pull request #549
Opened 2024-12-03 22:05 UTC by RKuttruff

## Description
- Implemented PGE classes (pre, post, exec) as child classes of the base PGE classes
- Added unit test stub and config YAML
- Added dockerfile + build & test scripts
- Added runconfig schema file + black files for future templates (MPC, ISO XML)

## Affected Issues
- #548 

## Testing
- Added unit test module for DIST-S1 PGE
- Added CI script for unit testing
- DID NOT add CI script for int testing nor supporting QA/comparison scripts for int testing
- DID NOT update Jenkins pipeline definitions to support this PGE in default builds (I made the changes but held back on committing them)

2024-12-03 22:11 UTC, RKuttruff commented on .ci/docker/Dockerfile_dist_s1
> +    && python -m pip install -r ${PGE_DEST_DIR}/opera/requirements.txt \
The pip install is failing without g++ installed
We should coordinate with ADT to have a numpy image <2 installed in the SAS so we won't have to worry about rebuilding it here, but it seems the issue is also present in the mgrs install.

2024-12-05 18:26 UTC, collinss-jpl requested changes
Overall looks great, mostly just some cut/paste gremlins to take care of

2024-12-05 19:56 UTC, RKuttruff commented on .ci/scripts/dswx_ni/build_dswx_ni.sh
> +printf "pge_version: ${TAG}\pge_build_datetime: ${BUILD_DATE_TIME}\n" \
Oops, mistook that for a typo without actually reading the text of the print statement...

2024-12-05 20:06 UTC, RKuttruff commented
@collinss-jpl Addressed findings

2024-12-05 21:12 UTC, merged